services:
#region -------------------------------------rabbitmq
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

#region -------------------------------------portainer
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"

#region ------------------------------------- main
  main.api:
    container_name: main.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=http://+:8080
      - "ConnectionStrings__Root=Server=maindb;Database=MainDb;User Id=sa;Password=@Moghanloo368;TrustServerCertificate=True;"
      - "GrpcSettings__HistoryUrl=http://logs.grpc:8080"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
    restart: always
    depends_on:
      - maindb
      - rabbitmq
    ports:
      - "8001:8080"

  maindb:
    container_name: main.db
    environment:
      SA_PASSWORD: "@Moghanloo368"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "14330:1433"
    volumes:
      - maindb_data:/var/opt/mssql

#region ------------------------------------- logs
  logs.api:
    container_name: logs.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__Root=mongodb://logsdb:27017"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
    restart: always
    depends_on:
      - logsdb
      - rabbitmq
    ports:
      - "8003:8080"

  logs.grpc:
    container_name: logs.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__Root=mongodb://logsdb:27017"
    restart: always
    depends_on:
      - logsdb
    ports:
      - "8004:8080"

  logsdb:
    container_name: logs.db
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

#region ---------------------------------------- files
  files.api:
    container_name: files.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__Root=Server=filesdb;Port=5432;Database=Files;User Id=admin;Password=@Moghanloo368"
    restart: always
    depends_on: 
      filesdb:
        condition: service_healthy
    ports:
      - "8005:8080"

  filesdb:
    container_name: filesdb
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=@Moghanloo368
      - POSTGRES_DB=Files
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

#region ---------------------------------------- pgadmin
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=@Moghanloo368
    restart: always
    ports:
      - "8007:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  #region ---------------------------------------- ocelotapigw
  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - files.api
      - logs.api
      - main.api
    ports:
      - "8010:80"

#region ---------------------------------------- files
  identity.domain.api:
    container_name: identity.domain.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - "DatabaseSettings__Root=Server=identitydb;Port=5432;Database=IdentityDB;User Id=admin;Password=@Moghanloo368"
    restart: always
    depends_on: 
      filesdb:
        condition: service_healthy
    ports:
      - "8006:8080"
      - "8006:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  identitydb:
    container_name: identitydb
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=@Moghanloo368
      - POSTGRES_DB=IdentityDB
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
