<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>57ed8798-6b89-449c-bad7-6e12930ff164</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SharedLibrary\SharedLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Blazored.LocalStorage">
      <HintPath>..\..\..\..\..\DLLs\Blazored.LocalStorage.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
