<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SharedLibrary\SharedLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Blazored.LocalStorage">
      <HintPath>..\..\..\..\..\DLLs\Blazored.LocalStorage.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
