<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\SharedLibrary\SharedLibrary.csproj" />
    <ProjectReference Include="..\Identity.Domain.Application\Identity.Domain.Application.csproj" />
    <ProjectReference Include="..\Identity.Domain.Infra.Data\Identity.Domain.Infra.Data.csproj" />
  </ItemGroup>

</Project>
