<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.4" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
		<PackageReference Include="NUnit" Version="4.3.2" />
		<PackageReference Include="NUnit.Analyzers" Version="4.7.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Autofac" Version="8.0.0" />
		<PackageReference Include="FluentAssertions" Version="6.12.1" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.7" />
		<PackageReference Include="Selenium.Support" Version="4.23.0" />
		<PackageReference Include="Selenium.WebDriver" Version="4.23.0" />
		<PackageReference Include="Shouldly" Version="4.2.1" />
		<PackageReference Include="SpecFlow.NUnit" Version="3.9.74" />
		<PackageReference Include="SpecFlow.Plus.LivingDocPlugin" Version="3.9.57" />
		<PackageReference Include="WebDriverManager" Version="2.17.4" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\Services\Identity\Identity.Domain.Api\Identity.Domain.Api.csproj" />
	  <ProjectReference Include="..\..\src\Services\Identity\Identity.Domain.Infra.Data\Identity.Domain.Infra.Data.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="NUnit.Framework" />
	</ItemGroup>

</Project>
